#!/system/bin/sh
# AOSGP TWEAKS
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

$busybox rm -f $LS
$busybox touch $LS


if [ -e /sys/devices/system/cpu/sched_mc_power_savings ]; then 
$busybox echo "2" > /sys/devices/system/cpu/sched_mc_power_savings
fi

if [ "`$busybox grep 2 /sys/devices/system/cpu/sched_mc_power_savings`" ]; then
$busybox echo "Feature enabled" | $busybox tee -a $LS; else
$busybox echo "This feature is not avaible for you, because your device is not multi core or your CPU doesn't support it" | $busybox tee -a $LS
fi
