#!/system/bin/sh
# AOSGP TWEAKS
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

if [ -e $PMB ]; then
busybox	rm $PMB;
fi;


# AOSGP Default =========================================#

busybox sysctl -e -w kernel.random.read_wakeup_threshold=128;
busybox sysctl -e -w kernel.random.write_wakeup_threshold=256;

busybox sleep 1

if [ /proc/sys/kernel/random/read_wakeup_threshold=128 ]; then
busybox echo "Optimization : Default = Activated..." | tee -a $PMB; else
busybox echo "Optimization : Default = Not Activated..." | tee -a $PMB;
fi;

busybox echo "" | tee -a $PMB;
busybox echo "# END : $( date +"%m-%d-%Y %H:%M:%S" ) " | tee -a $PMB
