#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox=/system/etc/L_SPEED/00L_STUFF/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
mount -o remount,rw /data 2>/dev/null
mount -o remount,rw /cache 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o remount,rw /data 2>/dev/null
$busybox mount -o remount,rw /cache 2>/dev/null

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/LS_cleaner.log

$busybox rm -f $LS
$busybox touch $LS

$busybox echo "# L Speed log" | $busybox tee -a $LS
$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Cleaner script is running..." | $busybox tee -a $LS

# cleaner
$busybox rm -f /cache/*.apk 2 > /dev/null
$busybox rm -f /cache/*.tmp 2 > /dev/null
$busybox rm -f /cache/*.log 2 > /dev/null
$busybox rm -f /cache/*.txt 2 > /dev/null
$busybox rm -f /cache/recovery/* 2 > /dev/null
$busybox rm -f /data/*.log 2 > /dev/null
$busybox rm -f /data/*.txt 2 > /dev/null
$busybox rm -f /data/anr/*.log 2 > /dev/null
$busybox rm -f /data/anr/*.txt 2 > /dev/null
$busybox rm -f /data/backup/pending/*.tmp 2 > /dev/null
$busybox rm -f /data/cache/*.* 2 > /dev/null
$busybox rm -f /data/dalvik-cache/*.apk 2 > /dev/null
$busybox rm -f /data/dalvik-cache/*.tmp 2 > /dev/null
$busybox rm -f /data/dalvik-cache/*.log 2 > /dev/null
$busybox rm -f /data/dalvik-cache/*.txt 2 > /dev/null
$busybox rm -f /data/data/*.log 2 > /dev/null
$busybox rm -f /data/data/*.txt 2 > /dev/null
$busybox rm -f /data/log/*.log 2 > /dev/null
$busybox rm -f /data/log/*.txt 2 > /dev/null
$busybox rm -f /data/local/*.apk 2 > /dev/null
$busybox rm -f /data/local/*.log 2 > /dev/null
$busybox rm -f /data/local/*.txt 2 > /dev/null
$busybox rm -f /data/local/tmp/*.log 2 > /dev/null
$busybox rm -f /data/local/tmp/*.txt 2 > /dev/null
$busybox rm -f /data/last_alog/*.log 2 > /dev/null
$busybox rm -f /data/last_alog/*.txt 2 > /dev/null
$busybox rm -f /data/last_kmsg/*.log 2 > /dev/null
$busybox rm -f /data/last_kmsg/*.txt 2 > /dev/null
$busybox rm -f /data/mlog/* 2 > /dev/null
$busybox rm -f /data/tombstones/*.log 2 > /dev/null
$busybox rm -f /data/tombstones/*.txt 2 > /dev/null
$busybox rm -f /data/system/*.log 2 > /dev/null
$busybox rm -f /data/system/*.txt 2 > /dev/null
$busybox rm -f /data/system/dropbox/*.log 2 > /dev/null
$busybox rm -f /data/system/dropbox/*.txt 2 > /dev/null
$busybox rm -f /data/system/usagestats/*.log 2 > /dev/null
$busybox rm -f /data/system/usagestats/*.txt 2 > /dev/null
$busybox rm -rf /sd*/LOST.DIR 2 > /dev/null

export sampling_rate=10000
export up_threshold=80

$busybox echo "memory cleaner--------[OK]" | $busybox tee -a $LS

if [ -e /data/anr/*.* ]; then
	$busybox echo "-anr not cleaned" | $busybox tee -a $LS
else
	$busybox echo "-anr cleaned" | $busybox tee -a $LS
fi
if [ -e /data/local/tmp/*.* ]; then
	$busybox echo "-local/tmp not cleaned" | $busybox tee -a $LS else
	$busybox echo "-local/tmp cleaned" | $busybox tee -a $LS
fi
if [ -e /data/cache/*.* ]; then
	$busybox echo "-cache not cleaned" | $busybox tee -a $LS
else
	$busybox echo "-cache cleaned" | $busybox tee -a $LS
fi
if [ -e /data/last_log/*.* ]; then
	$busybox echo "-log not cleaned" | $busybox tee -a $LS
else
	$busybox echo "-log cleaned" | $busybox tee -a $LS
fi
if [ -e /data/tombstones/*.* ]; then
	$busybox echo "-tombstones not cleaned" | $busybox tee -a $LS
else
	$busybox echo "-tombstones cleaned" | $busybox tee -a $LS
fi

$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) All junk directories are now cleaned,Thanks to -CALIBAN666@XDA-!" | $busybox tee -a $LS
