#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox=/system/etc/L_SPEED/00L_STUFF/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/LS_better_scrolling.log

$busybox rm -f $LS
$busybox touch $LS

$busybox echo "# L Speed log" | $busybox tee -a $LS
$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Enabling better scolling.." | $busybox tee -a $LS

# Scrolling cache
setprop persist.sys.scrollingcache 3

$busybox echo "Scrolling cache disabled.." | $busybox tee -a $LS

setprop ro.max.fling_velocity 12000
setprop ro.min.fling_velocity 8000
setprop touch.pressure.scale 0.001

$busybox echo "Other parameters tweaked.." | $busybox tee -a $LS

$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Better scrolling is enabled" | $busybox tee -a $LS
