#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox=/system/etc/L_SPEED/00L_STUFF/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/LS_kernel_tweaks.log

$busybox rm -f $LS
$busybox touch $LS

$busybox echo "# L Speed log" | $busybox tee -a $LS
$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Adding kernel tweaks.." | $busybox tee -a $LS

#Dynamic fsync
if [ -e /sys/kernel/dyn_fsync/Dyn_fsync_active ]; then
       $busybox echo "1" > /sys/kernel/dyn_fsync/Dyn_fsync_active
fi
if [ -e /sys/kernel/dyn_fsync/Dyn_fsync_active ]; then
$busybox echo "Dyn_fsync enabled" | $busybox tee -a $LS
else
$busybox echo "Dyn_fsync doesn't exist on your kernel" | $busybox tee -a $LS
fi

#FS tweak
$busybox sysctl -w fs.lease-break-time=5
$busybox sysctl -w fs.inotify.max_queued_events=32000
$busybox sysctl -w fs.inotify.max_user_instances=256
$busybox sysctl -w fs.inotify.max_user_watches=10240

$busybox echo "File system parameters are updated" | $busybox tee -a $LS

$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Kernel tweaks added" | $busybox tee -a $LS
