#!/system/bin/sh
# PROJECT MOD BOOST EDITION  
# NITRO X_SPARK EDITION V-II™ 
# Copyright (C) 2015 K1ks
# From Darky's zipalign but modified

# ZipAlign =========================================#

LOG_FILE=/system/etc/Nitro/X00ZIP.log
ZIPALIGNDB=/system/etc/Nitro/zipalign.db

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;

busybox mount -o rw,remount /system;

echo "Starting FV Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;

for DIR in /system/app /data/app /system/priv-app;
do
	cd $DIR;
	for APK in *.apk */*.apk;
	do
		if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]; then
			echo "Already checked: $DIR/$APK" | tee -a $LOG_FILE;
		else
			ZIPCHECK=`/system/xbin/zipalign -c -v 4 $APK | grep FAILED | wc -l`;
			if [ $ZIPCHECK == "1" ]; then
				echo "Now aligning: $DIR/$APK" | tee -a $LOG_FILE;
				/system/xbin/zipalign -f 4 $APK /data/local/$APK;
				rc = "$?";
				if [ $rc -eq 0 ]; then
					if [ -e "/data/local/$APK" ]; then
						cp -f -p "/data/local/$APK" "$APK" | tee -a $LOG_FILE;
						rm -f "/data/local/$APK";
						grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
					else
						echo "ZipAligning $APK Failed (no output file)"  | tee -a $LOG_FILE;
					fi;
				else
					[ -f "/data/local/$APK" ] && rm -f "/data/local/$APK"
					echo "ZipAligning $APK Failed (rc: $rc)"  | tee -a $LOG_FILE;
				fi;
			else
				echo "Already aligned: $DIR/$APK" | tee -a $LOG_FILE;
				grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
			fi;
		fi;
	done;
done;

busybox mount -o ro,remount /system;
busybox touch $ZIPALIGNDB;
busybox echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;
